### ISSUE TITLE
Does the I stand for Interface?

### ISSUE THREAD

**Issue by aranw** [gonzalo123/using#1]
Just wondering if the I in `IDisposable` stands for Interface?

If so why bother adding it like that? Why not put `DisposableInterface` like other Interfaces used in projects like StackPHP, Symfony2, Laravel, Silex?

Another benefit of naming it this will be users can know at a glance that it is a Interface.

Edit: Fixed spelling

**Comment by gonzalo123** [comment]
I use IDisposable only because it's the name that c# uses. You are not the
first one who said that. Maybe I need to change according to PHP standards.
(or maybe a SPL iface)

(I had a misspel in the library just updated. disposable instead of
disponsable )

**Comment by aranw** [comment]
I think using the standard thats come with PHP packages like Symfony2 and Laravel would be best. I personally never seen any SPL iface interfaces? 

It also reads as you expect `DisposableInterface`
